# Generated by Django 5.0.6 on 2024-06-20 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='expires_at',
        ),
    ]
